# Interpolating term structure for ensemble runs

The Bauer & Rudebusch (2022) paper gives 4 term structures for 4 discount rates of 1.5%, 2%, 3%, and 5%. We want the term structure of the 4.25% discount rate that is consistent with their framework. So here we bilinearly interpolate the pure rate of time preference and the elasticity of intertemporal substitution to arrive at the discount rate.

In [24]:
import numpy as np
import matplotlib.pyplot as plt 

from scipy.interpolate import interp2d
from mpl_toolkits.mplot3d import Axes3D

In [63]:
prtps = np.asarray([0.1, 0.2, 0.5, 0.8, 2.4])
eiss = np.asarray([0.93, 1.2, 1.42, 1.53, 1.86])
dis_rates = np.asarray([1.5, 2, 2.5, 3, 5])

In [64]:
interp_disrates= interp2d(prtps, eiss, dis_rates, kind='linear')

In [67]:
interp_prtps = np.linspace(0.1, 2.5, 10000)
interp_eiss = np.linspace(0.93, 1.86, 10000)
interp_dis_rates = interp_disrates(interp_prtps, interp_eiss)

interp_dis_rates

array([[1.50798508, 1.50816705, 1.50834902, ..., 3.25168302, 3.25168302,
        3.25168302],
       [1.50811687, 1.50829884, 1.50848082, ..., 3.25185801, 3.25185801,
        3.25185801],
       [1.50824866, 1.50843064, 1.50861262, ..., 3.25203299, 3.25203299,
        3.25203299],
       ...,
       [2.82549785, 2.82572489, 2.82595193, ..., 5.00104136, 5.00104136,
        5.00104136],
       [2.82562965, 2.82585669, 2.82608373, ..., 5.00121635, 5.00121635,
        5.00121635],
       [2.82576144, 2.82598848, 2.82621553, ..., 5.00139134, 5.00139134,
        5.00139134]])

In [68]:
np.where(interp_dis_rates >= 4.25)

(array([5706, 5706, 5706, ..., 9999, 9999, 9999]),
 array([9582, 9583, 9584, ..., 9997, 9998, 9999]))

In [73]:
interp_dis_rates[np.where(interp_dis_rates >= 4.25)]

array([4.25008855, 4.25016643, 4.25016643, ..., 5.00139134, 5.00139134,
       5.00139134])

In [74]:
prtp_ind = np.where(interp_dis_rates >= 4.25)[0][0]
eis_ind = np.where(interp_dis_rates >= 4.25)[1][0]

In [76]:
prtp = interp_prtps[prtp_ind]
eis = interp_eiss[eis_ind]

prtp, eis

(1.4695769576957696, 1.8212151215121513)

In [77]:
# check
prtp + 1.5 * eis

4.201399639963997